rubymonsters/slam-alphas

- app/assets/javascripts/users.coffee
- app/assets/stylesheets/scaffolds.scss
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/index.html.erb
- app/views/users/index.json.jbuilder
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- app/views/users/show.json.jbuilder
- config/routes.rb
- db/migrate/20160606173555_create_users.rb
- db/schema.rb
- test/controllers/users_controller_test.rb
- test/fixtures/users.yml
- test/models/user_test.rb
Correct Scaffolding
rails g scaffold User name city country email age:integer
This PR adds the User model with
name
city
country 
email
age
(along with other folders and files) via the command rails g scaffold name city country email age:integer to the project. If you want to learn more about Scaffolding, please find infos here under point 5.
If you get stuck when playing around a bit, this wiki page might be helpful.
> correct scaffold command adding User

- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
This PR adds the pg gem and configures the database with PostgreSQL
> Postgres setup

- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
- app/views/shared/_navigation.html.erb
- config/routes.rb
> Add navigation Bar

- app/controllers/users_controller.rb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- db/migrate/20160620180306_add_website_to_users.rb
- db/schema.rb
Allows the user to add a website
> User can add website

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/validators/email_validator.rb
- app/validators/website_validator.rb
- app/views/users/index.html.erb
- config/application.rb
deleted unnecesary code line in config
> Replace regex validation

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/index.html.erb
- db/migrate/20160815174813_add_facebook_link_to_users.rb
- db/schema.rb
This PR does following:
- adds column `facebook_link` to users in the database
- adds `Facebook link` field to users form & validates it
Related issue: #5
> Add facebook link to users form

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/users.scss
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/users/index.html.erb
- db/migrate/20160829180902_add_latitude_and_longitude_to_user.rb
- db/schema.rb
Please see commit messages
This fixes issue #19 
Please merge! :)
> Create a map

- app/controllers/maps_controller.rb
- app/models/user.rb
- app/views/maps/show.html.erb
- app/views/users/_form.html.erb
- app/views/users/index.html.erb
- config/routes.rb
- db/schema.rb
Add a view user by country
Pass country code to the database but show it to the user as country name
Added the support (center, zoom size) for three maps
> Country maps

- db/migrate/20161219190441_add_public_and_admin_to_users.rb
- db/schema.rb
This PR adds admin and public as columns to the users table.
Solves Github issue #32
> Add admin and public columns

- Gemfile
- app/assets/images/marker-blue.svg
- app/assets/images/marker-red.svg
- app/assets/images/marker-turquoise.svg
- app/assets/javascripts/application.js
- app/assets/javascripts/main-wp.js
- app/assets/stylesheets/base.sass
- app/assets/stylesheets/main-wp.css
- app/assets/stylesheets/map.sass
- app/assets/stylesheets/users.scss
- app/controllers/maps_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/maps/show.html.erb
- app/views/shared/_list.html.erb
- app/views/shared/_navigation.html.erb
- app/views/users/show.html.erb
- config/routes.rb
Current state:
The maps controller lists all users. Those can be replaces by more sophisticated lists (unique letters of the alphabet in one, starting a new section with the new letter in the other)
> User list frontend

- db/seeds.rb
I added the two admins to the Test Data-
Was not sure about the extra columns `video`, `train connection` and `availability`.
Thats why I left them commented.
This PR solves #29
> added two admins into seed.rb

- app/controllers/maps_controller.rb
- app/views/shared/_list.html.erb
Puts users with same first letter of name in the correct section.
cc @freddax
> Fix user list ordering

- app/assets/stylesheets/admin.sass
- app/views/layouts/application.html.erb
- app/views/passwords/create.html.erb
- app/views/passwords/new.html.erb
- app/views/sessions/_form.html.erb
- app/views/sessions/new.html.erb
- app/views/shared/_adminbar.html.erb
- app/views/shared/_navigation.html.erb
- app/views/users/_form.html.erb
- app/views/users/new.html.erb
Make some forms pretty
plus the admin topbar
> More admin UI

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/views/users/show.html.erb
I have some questions, regarding this pull request, some directly related to the code and some not. 
**Unrelated to the code**: As I was adding the files to be commited I noticed that Gemfile.lock and db/schema.rb had changed. However I didn't commit them.  In the Gemfile turbolinks and coffee rails were deleted & in the schema file  the time stamps were deleted and added again. Why does this happen and what is a good practice in these cases?
**Related to the code** :
1) I added a line ` helper_method :signed_in_as_admin? `within the ApplicationController .  But I think I could have also added the method to the  ApplicationHelper . 
How do you know what is best? and where should you add the method?
2) I could not test in the browser if this code really works since atm it is only possible …
> Remove links

- app/assets/stylesheets/main-wp.css.erb
- app/views/users/show.html.erb
> Change wording and language to german for Edit and Back

- app/assets/stylesheets/flashes.sass
- app/views/layouts/application.html.erb
- app/views/sessions/_form.html.erb
- app/views/users/_form.html.erb
> Styles for error messages

- app/assets/javascripts/main-wp.js
- app/assets/stylesheets/flashes.sass
- app/assets/stylesheets/map.sass
- app/views/maps/show.html.erb
- app/views/shared/_list.html.erb
> Color clusters, also fix jump links in alphabetical nav

- app/assets/stylesheets/main-wp.css.erb
- app/assets/stylesheets/map.sass
- app/assets/stylesheets/profile.sass
- app/assets/stylesheets/user.sass
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/views/maps/show.html.erb
- app/views/shared/_adminbar.html.erb
- app/views/shared/_map.erb
- app/views/shared/_navigation.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
(still waiting for the `user_alpha_or_recommended` helper from another PR)
User#index for non-logged-in users
User#index for logged in admins
New map
> User UX tweaks for admins and non-JS, closes #73

- app/models/user.rb
- app/views/users/_form.html.erb
- db/schema.rb
As all fields are to be mandatory, we thought, a statement at the top of the form might bed better that marking every single field with *. What do you think?
++++++++++
update: we saw only then, that two fields are to be optional after all
therefore, this branch contains:
#115 as requested with *
#112 make facebook link and website fields optional
#110 add the space in Slam Alphas in the "recommended by" form field
> Add a paragraph on mandatory fields

- app/assets/javascripts/main-wp.js
- app/assets/stylesheets/admin.sass
- app/assets/stylesheets/base.sass
- app/assets/stylesheets/flashes.sass
- app/assets/stylesheets/profile.sass
- app/helpers/users_helper.rb
- app/views/users/show.html.erb
- db/schema.rb
- db/seeds.rb
- spec/helpers/user_helper_spec.rb
includes video player decision logic (youtube/ vimeo) as well as the embed helper and the front end UI
> Add video player

- app/assets/javascripts/main-wp.js
- app/assets/stylesheets/flashes.sass
- app/assets/stylesheets/map.sass
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
> flash close and fb link fix

- app/assets/stylesheets/user.sass
- app/controllers/users_controller.rb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
Button added, CSS needs to be adjusted (formatting is just provisional)
#109
> Add button to delete profile in edit view

- app/assets/javascripts/main-wp.js
- app/assets/stylesheets/base.sass
- app/assets/stylesheets/flashes.sass
- app/assets/stylesheets/layout.sass
- app/assets/stylesheets/profile.sass
- app/helpers/users_helper.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- spec/helpers/user_helper_spec.rb
link to country overview when closing profile, close #114
Change wording of 'keine Reisebereitschaft' to 'zur Zeit keine' #135 
make Video link appear like a button #132 
Make all links in contact section open in new tab #137
Revisit show facebook button logic #136
> More things

- app/assets/javascripts/main-wp.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/layout.sass
- app/assets/stylesheets/map.sass
- app/assets/stylesheets/profile.sass
- app/views/shared/_list.html.erb
- app/views/users/show.html.erb
> Mobile style

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- db/migrate/20170703192614_add_travels_via_to_users.rb
- db/schema.rb
This PR introduces the form input field `travels_via` for users to allow traveling by car, bus, etc.
Subtask of #75.
> ®Feat/input field travels via

- app/helpers/users_helper.rb
> make recommended by optional

- README.md
- env.SAMPLE
This PR solves Issue #51 
hopefully;)
> created envsample file again:)

- app/mailers/user_mailer.rb
- app/views/user_mailer/account_added.erb
- lib/tasks/profiles.rake
magic local command
```
cat lib/tasks/slam-alphas-daten-2.csv | heroku run rake profiles:import
```
> add profile import task
